apiVersion: v1
kind: Service
metadata:
  name: wil-app
  labels:
    app: wil-app
spec:
  type: NodePort
  selector:
    app: wil-app
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
